# Team 13, Melbourne
# Jing Qiu, 1152016, jiqiu1@student.unimelb.edu.au
# Meijun Yue, 1190161, meijuny@student.unimelb.edu.au
# Suyi Jiao, 1222833, sjjiao@student.unimelb.edu.au
# Yeting Wu, 1310061, yetingw@student.unimelb.edu.au
# Wenshuo Pan, 1226506, wenshuop@student.unimelb.edu.au

#---
#- name: Create Website directory
#  become: yes
#  ansible.builtin.file:
#    path: "{{ wb_dir }}"
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#    recurse: yes
#    state: directory
#
#- name: Configure compose
#  become: yes
#  ansible.builtin.template:
#    src: docker-compose.yaml.j2
#    dest: "/home/ubuntu/COMP90024/comp90024as2/website_build/docker-compose.yaml"
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#
#- name: Run docker compose
#  become: yes
#  community.docker.docker_compose:
#    project_src: "/home/ubuntu/COMP90024/comp90024as2/website_build/"
#    pull: yes
#    state: present
#    remove_orphans: yes
#    recreate: always

- name: Shut down previous website server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /home/ubuntu/COMP90024/comp90024as2/website_build


- name: Start website server
  become:
    yes
  shell: docker-compose up  --build -d
  args:
    chdir: /home/ubuntu/COMP90024/comp90024as2/website_build