# Team 13, Melbourne
# Jing Qiu, 1152016, jiqiu1@student.unimelb.edu.au
# Meijun Yue, 1190161, meijuny@student.unimelb.edu.au
# Suyi Jiao, 1222833, sjjiao@student.unimelb.edu.au
# Yeting Wu, 1310061, yetingw@student.unimelb.edu.au
# Wenshuo Pan, 1226506, wenshuop@student.unimelb.edu.au

- hosts: instances
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: false
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/mrccloud.key
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: installDependencies
    - role: deployMountVolumes
    - role: docker
    # - role: wordpress