# Team 13, Melbourne
# Jing Qiu, 1152016, jiqiu1@student.unimelb.edu.au
# Meijun Yue, 1190161, meijuny@student.unimelb.edu.au
# Suyi Jiao, 1222833, sjjiao@student.unimelb.edu.au
# Yeting Wu, 1310061, yetingw@student.unimelb.edu.au
# Wenshuo Pan, 1226506, wenshuop@student.unimelb.edu.au

---

# add proxy to allow instances to be accessible externally
- name: add proxy to /etc/environment
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      http_proxy=http://wwwproxy.unimelb.edu.au:8000/
      https_proxy=http://wwwproxy.unimelb.edu.au:8000/
      no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au
- name: Reboot machine
  become: yes
  reboot:
    reboot_timeout: 3000