# Team 13, Melbourne
# Jing Qiu, 1152016, jiqiu1@student.unimelb.edu.au
# Meijun Yue, 1190161, meijuny@student.unimelb.edu.au
# Suyi Jiao, 1222833, sjjiao@student.unimelb.edu.au
# Yeting Wu, 1310061, yetingw@student.unimelb.edu.au
# Wenshuo Pan, 1226506, wenshuop@student.unimelb.edu.au

---
# Install dependencies on the host
- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  ansible.builtin.pip:
    name: ['pip', 'openstacksdk']
    state: latest
# pip install --upgrade pip && pip install openstacksdk
