---
- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /home/ubuntu/COMP90024/comp90024as2/harvest

- name: Start server
  become:
    yes
  shell: docker-compose up  --build -d
  args:
    chdir: /home/ubuntu/COMP90024/comp90024as2/harvest