# Team 13, Melbourne
# Jing Qiu, 1152016, jiqiu1@student.unimelb.edu.au
# Meijun Yue, 1190161, meijuny@student.unimelb.edu.au
# Suyi Jiao, 1222833, sjjiao@student.unimelb.edu.au
# Yeting Wu, 1310061, yetingw@student.unimelb.edu.au
# Wenshuo Pan, 1226506, wenshuop@student.unimelb.edu.au

---

- name: copy github ssh key
  copy:
    src: git_key
    dest: /home/ubuntu/.ssh/git_key
    owner: ubuntu
    group: ubuntu
    mode: 0600


- name: configure ssh to use ansible key for github.com
  template:
    src: host_vars/git_ssh_config
    dest: /home/ubuntu/.ssh/config
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Delete remote working directory if exists
  file:
    state: absent
    path: '{{ wb_dir }}'

- name: Creates remote working directory
  file:
    path: '{{ wb_dir }}'
    state: directory
    mode: 0755

- name: git clone
  shell: git clone git@github.com:wenshuop/comp90024as2.git --config core.sshCommand="ssh -i /home/ubuntu/.ssh/git_key"
  args:
    chdir: '{{ wb_dir }}'

- name: Remove GitHubKey
  file:
    path: /home/ubuntu/.ssh/git_key
    state: absent