# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: mrccloud
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: instance1-volume
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance2-volume
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance3-volume
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance4-volume
    vol_size: 100
    device: /dev/vdb
    mountpoint: /data


# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_http
    description: "security group for instance server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance1
    volumes: ['instance1-volume']
  - name: instance2
    volumes: ['instance2-volume']
  - name: instance3
    volumes: ['instance3-volume']
  - name: instance4
    volumes: ['instance4-volume']
vars:
  - ansible_user: ubuntu
  - ansible_ssh_private_key_file: ~/mrccloud.key
  - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

couchdb_image: ibmcom/couchdb3:latest
couchdb_user: admin
couchdb_pass: admin
couchdb_VERSION: "3.2.1"
couchdb_cookie: "a192aeb9904e6590849337933b000c99"
couchdb_uuid: "098a5f4412d0accbd973f9f848a97246"
cluster_name: "_cluster_setup"
couchdb_container_name: "couchdb_"
couchdb_port: 5984

wb_dir: website_build

# Wordpress / MySQL
database_name: wordpress
database_user: wordpress
database_password: wordpress
mysql_root_password: "P@ssw0rd"

